import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReduxProvider from "./reduxProvider/ReduxProvide";
import { Toaster } from "@/components/ui/sonner";
import { useDispatch } from "react-redux";
import { useEffect } from "react";
import { hydrateHero } from "../store/features/heroSlice/HeroSlice";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const dispatch = useDispatch();

  useEffect(() => {
    // Sahifa brauzerda yuklanishi bilan localStorage'dan ma'lumotlarni Redux'ga olib o'tamiz
    dispatch(hydrateHero());
  }, [dispatch]);
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          {children}
          <Toaster richColors toastOptions={{
            className: "bg-zinc-900 border-zinc-800 text-white rounded-2xl", // Umumiy ko'rinish
            style: {
              border: '1px solid #27272a',
              padding: '16px',
            },
            // Turli holatlar uchun ranglar
          }} />
        </ReduxProvider>
      </body>
    </html>
  );
}
