import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReduxProvider from "./reduxProvider/ReduxProvide";
import { Toaster } from "@/components/ui/sonner";
import ClientInit from "@/components/ClinitInit";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// Metadata endi xatosiz ishlaydi, chunki bu Server Component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}>
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <ClientInit /> {/* Redux mantiqi shu yerda ishlaydi */}
          {children}
          <Toaster richColors />
        </ReduxProvider>
      </body>
    </html>
  );
}